services:
  postgres:
    image: postgres:16
    container_name: postgres-local
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-local:/var/lib/postgresql/data
      # 初期化SQL使う場合は以下を有効に
      # - ./src/frameworks-drivers/db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file:
      - .env.local
    networks:
      - local-network

volumes:
  postgres-local:

networks:
  local-network:
    external: true